### PR TITLE
PAH-470 update dependencies

### PR DESCRIPTION
**Pull request by juliaanholcer**
- Update dependencies.

Note: "stylelint-processor-html@1.0.0" is deprecated and it seems that we might not use the scss preprocessor for stylelint, because its latest version should be able to handle .vue files, however, removing this package or replacing it with non-deprecated preprocessor will cause that style linter doesn't work at all. Sorry, but I have no idea how to solve it so this package stays.

@arturtamborski I'm not quite sure which dependencies you meant as unused.

### CODE REVIEW

**Comment by juliaanholcer** [comment]
Haha, it seems that now eslint works and there is a lot of lint errors in the code ;-)

**Comment by arturtamborski** [comment]
> Sorry, but I have no idea how to solve it so this package stays.
unfortunately I can't really help you here. I guess it's not that big of a deal, certainly not compared to all other packages updated/removed :)

> Haha, it seems that now eslint works and there is a lot of lint errors in the code ;-)
yes, but there's a simple way to fix it:
```
make bash-frontend
npm run lint:fix
```
aaand `git add .` :) there will still be 11 errors that need to be fixed by hand, but that's a lot less than ~80 originally reported.

**Comment by juliaanholcer** [comment]
Remaining problems arise from dependency cycles, i.e. auth.js imports some stuff from http.js and vice versa. One can take shortcuts and disable eslint for these imports, but we may need to check if such code is optimal. Unfortunately, many things in the current vershion are new to me. @pniedzwiedzinski , do you have an idea of how to refactor to avoid these cyclical dependencies?

**Comment by pniedzwiedzinski** [comment]
We could divide `auth.js` into 2 parts:
- interacting with `localStorage` (`getToken`, `getAuthHeader`)
- interacting with api (that's `http.js` is imported for)

But as in #459  (#421) we will remove localStorage, so this is a temporary fix.

**Comment by pniedzwiedzinski** [comment]
This should fix it: [circular-import.patch.txt](https://github.com/CodeForPoznan/pah-fm/files/4610332/circular-import.patch.txt)

Run `git apply /path/to/circular-import.patch.txt` in pah-fm root dir

**Comment by pniedzwiedzinski** [comment]
@juliaanholcer what's the status on that?

**Comment by juliaanholcer** [comment]
> @juliaanholcer what's the status on that?

I'm going to finish it but unfortunately not this week, sorry.

**Review by pniedzwiedzinski — APPROVED** [review]

**Comment by arturtamborski** [comment]
Will reopen with new updates, this one is too old to bother fixing.

**Pull request closed without merging**
